---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands: null
  build:
    commands:
      - npm install
      - ng build
      - pwd
      - ls -al
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - dist/**/*
